---
    - name: install {{runtime}}
      yum:
         name={{runtime}}
         state=present

    - command: echo {{item}}
      loop: [0,2,4,6,8,10]
      when: item > 5

    - name: Install Java JDK rpm from local file
      yum: 
         name={{develop}}
         state=present

    - fail:
        msg: "Invalid version of {{runtime}}, you are looking for. "
      when: (java_type != 'openjdk')
